---
sbh:
  user: ~
  password: ~
logs:
  level: DEBUG
  token: ~

# The config file to pass to the metrics gatherer
metrics:
  config: /reactor.ini

tapis:
  destination: agave://data-sd2e-community/synbiohub/metrics/
